const mockData = [
  {
    Loan_ID: "LP001015",
    Gender: "Male",
    Married: "Yes",
    Dependents: "1",
    Education: "Graduate",
    Self_Employed: "Yes",
    ApplicantIncome: "2165",
    CoapplicantIncome: "3422",
    LoanAmount: "152",
    Loan_Amount_Term: "360",
    Credit_History: "1",
    Property_Area: "Urban",
  },
  {
    Loan_ID: "LP001022",
    Gender: "Male",
    Married: "Yes",
    Dependents: "1",
    Education: "Not Graduate",
    Self_Employed: "Yes",
    ApplicantIncome: "2178",
    CoapplicantIncome: "3422",
    LoanAmount: "152",
    Loan_Amount_Term: "360",
    Credit_History: "1",
    Property_Area: "Urban",
  },
  {
    Loan_ID: "LP001031",
    Gender: "Female",
    Married: "No",
    Dependents: "2",
    Education: "Graduate",
    Self_Employed: "Yes",
    ApplicantIncome: "2165",
    CoapplicantIncome: "3678",
    LoanAmount: "152",
    Loan_Amount_Term: "270",
    Credit_History: "1",
    Property_Area: "Urban",
  },
  {
    Loan_ID: "LP001035",
    Gender: "Female",
    Married: "Yes",
    Dependents: "1",
    Education: "Graduate",
    Self_Employed: "Yes",
    ApplicantIncome: "4517",
    CoapplicantIncome: "3422",
    LoanAmount: "152",
    Loan_Amount_Term: "270",
    Credit_History: "1",
    Property_Area: "Urban",
  },
];

export default mockData;
